### ISSUE TITLE
Make icons in tree-view optional?

### ISSUE THREAD

**Issue by tpoisot** [forivall/adwaita-pro-ui#2]
I like this theme, but I also like icons in tree-view. Any chance they might be optional? Gnome shell 3.12 has icons (see in nautilus, for example).

**Comment by forivall** [comment]
I pushed a new version that contains an option to turn the icons back on. You might also want to use https://atom.io/packages/file-icons for file specific icons. It supports more file types than gtk has native icons for, so it's not really worth it to try to get native icons working.
